version: '3.8'
services:
    mysql-server:
        image: mysql:5.7
        container_name: mysql-server
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'campingsPlaceMysql'
            MYSQL_PASSWORD: 'root'
        volumes:
            - ./mysql/src:/var/lib/mysql/
        ports:
            - 3307:3306

    php-myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: php-myadmin
        volumes:
            - ./phpmyadmin/src:/var/www/html/phpmyadmin
        environment:
            PMA_HOST: sql_CPN
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - 8081:80
        depends_on: 
            - mysql-server

    php-apache-environment:
        container_name: php-apache
        build:
            context: ./
            dockerfile: php/Dockerfile
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8000:80
        depends_on: 
            - mysql-server
