version: '3.7'

volumes:
    logs:
        driver: local

services:
    slimmain:
        image: php:8-alpine
        container_name: slimmain
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        depends_on:
            - mysqlmain
        networks:
            app-network:
                ipv4_address: 10.5.0.4
    mysqlmain:
        image: mysql:5.7
        container_name: mysqlmain
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'slimmysql'
            MYSQL_PASSWORD: 'root'
        ports:
        - "6033:3306"
        volumes: 
        - ./mysql_data:/var/lib/mysql
        networks:
            app-network:
                ipv4_address: 10.5.0.5
    phpmyadminmain:
        image: phpmyadmin/phpmyadmin
        container_name: pma_usermain
        links:
            - mysqlmain
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8081:80
        volumes:
            - ./phpmyadmin_data:/var/www/html/phpmyadmin
        depends_on:
            - mysqlmain
        networks:
            app-network:
                ipv4_address: 10.5.0.6

networks:
    app-network:
        driver: bridge
        ipam:
            config:
                - subnet: 10.5.0.0/16
                  gateway: 10.5.0.1
